### ISSUE TITLE
Order search by order number does not work with WooCommerce Sequential Order Numbers Pro

### ISSUE THREAD

**Issue by blockagency-co** [OllieJones/fast-woo-order-lookup#16]
I just noticed that the order search by order number is not working.

It may be because on the site where I have installed the plugin we are using this plugin: “WooCommerce Sequential Order Numbers Pro”.

Is it possible that it is incompatible with Fast Woo Order Lookup?

**Comment by OllieJones** [comment]
Yes, it is likely that [WooCommerce Sequential Order Numbers Pro](https://woocommerce.com/products/sequential-order-numbers-pro/) interferes with order number search in this plugin. I'll investigate.

**Comment by blockagency-co** [comment]
Hi again!

I just wanted to check if there are any plans to make this plugin compatible with "WooCommerce Sequential Order Numbers Pro"?

Thanks!!

**Comment by OllieJones** [comment]
This just in from the publisher of the plugin.


> Zach replied
> Sep 19, 10:57am
> Hello there,
> 
> Thank you for reaching out about our plugin, Sequential Order Numbers Pro! I'm happy to assist you with this. :)
> 
> I understand that you develop the plugin, Fast Woo Order Lookup, and are looking to make it compatible with our plugin, Sequential Order Numbers Pro. I am happy to help get you some information for integrating our plugin. 🙂
> 
> There are a few things to note, our plugin has some developer documentation on using the order numbers to get the actual order returned which may be useful to you when looking at creating compatibility. We also have some additional information on this in our FAQ section as well.
> 
> That said, there are also the following meta keys in the order to associate the various aspects of the Sequential Order Number Pro's meta data in the order:
> _order_number - This is the sequential number without any set prefix or suffix i.e 5228
> _order_number_formatted - This is the fully formatted order number that includes the prefix and suffix i.e SVT-5228-09-19-24
> _order_number_meta - This is an array of data that consists of the following data:
> prefix: SVT-
> suffix: -{M-D-YY}
> length: 4
> 
> Does that help to get you started with implementing the Sequential Order Numbers Pro order numbers with your plugin?
>

**Comment by OllieJones** [comment]
This is now available in 1.1.2.  If you already have the plugin activated, please deactivate it and reactivate it.
