### ISSUE TITLE
Is the FAQ note about slow meta key query still relevant?

### ISSUE THREAD

**Issue by MaximeMichaud** [OllieJones/fast-woo-order-lookup#21]
I noticed that the FAQ mentions the following:

"The orders page itself contains a very slow query (to be fixed in WooCommerce 9.0.0) to look up meta_keys. This fixes that query’s performance too."

This note seems to date back to before the release of WooCommerce 9.0.0. However, the recent commit (https://github.com/OllieJones/fast-woo-order-lookup/commit/39c8bca1f895356b5e358ab6f2a7a30e98647b28) appears to have implemented the fix in the code, applying a conditional check for WooCommerce versions below 9.0.0.

With WooCommerce 9.0.0 being available since May, and the fix for the slow meta_key query having been merged (https://github.com/woocommerce/woocommerce/pull/46985), is this note in the FAQ still relevant?

I've noticed your contributions and responses to related topics on WP and GitHub, and they’ve been very helpful. Just wondering if this FAQ entry should be updated or removed now that the fix is in place.

Thanks again for all your work!

**Comment by OllieJones** [comment]
Good cartch. Removed. Thanks.

**Comment by MaximeMichaud** [comment]
No Problem :D
