### ISSUE TITLE
fwol table is empty (still)

### ISSUE THREAD

**Issue by steveni1963** [OllieJones/fast-woo-order-lookup#26]
Hi Oliver,

Please see email replies to original issue after you closed it.

Apologies for not replying earlier

**Comment by MaximeMichaud** [comment]
Hi,
Oliver reopened [issue #9](https://github.com/OllieJones/fast-woo-order-lookup/issues/9)
This one can be closed now.

**Comment by OllieJones** [comment]
Dup #9
