### ISSUE TITLE
Build the trigram table in the background from wp_cron events

### ISSUE THREAD

**Issue by OllieJones** [OllieJones/fast-woo-order-lookup#4]
As of 0.1.4, the entire trigram table gets built right when the plugin is activated.

That's a timeout asking to happen. It needs to be done in batches kicked off by cronjobs.

**Comment by smgdarien** [comment]
Following

**Comment by OllieJones** [comment]
Yes. Done. [as_enqueue_async_action()](https://actionscheduler.org/api/#function-reference--as_enqueue_async_action) in the ActionScheduler component is pretty great. Makes this easy. And we know WooCommerce has it.
