### ISSUE TITLE
Indexing progress stuck at 0%

### ISSUE THREAD

**Issue by deeeeesign** [OllieJones/fast-woo-order-lookup#5]
Hi! I installed this on a woocommerce store, and after an hour the notice still says:

Fast Woo Order Lookup indexing still in progress. 0% complete.

**Comment by OllieJones** [comment]
Thanks for the feedback, and for trying out this plugin.

How many orders do you have, roughly, in your system?

Take a look at your ActionScheduler queue in WooCommerce -> Status -> Scheduled Actions.

There should be some actions on the hook "fast_woo_order_lookup_textdex_action". Are any pending? If you hover over any pending ones, you should be able to click Run. It would be good to know whether that helps.

**Comment by deeeeesign** [comment]
There are roughly 90,000 orders. Pulling up that screen, it looks like all the actions have completed, and the 0% complete message is now gone!

I just did a test search for an order, and it does seem to have shaved off some time, but not a ton. Down from 15 seconds to 9 seconds.

Thanks!

**Comment by OllieJones** [comment]
Thanks for following up. I guess I need to make the 0% message more informative. 

That speedup is a bit disappointing, of course. Sigh.

**Comment by OllieJones** [comment]
Hello, @deeeeesign  ... I have updated the plugin with a much faster search.  (hopefully).

Would you be willing to give it a try? 

https://www.plumislandmedia.net/wordpress-plugins/fast-woo-order-lookup/
