### ISSUE TITLE
fwol table is empty -- when columns use character sets other than $wpdb->charset.

### ISSUE THREAD

**Issue by steveni1963** [OllieJones/fast-woo-order-lookup#9]
I installed the plugin and performed some searches - same slow and missing results as previously.

After an hour I checked the fwol table size and it is empty.

**Comment by OllieJones** [comment]
I improved some code in v1.1.1 related to the creation of this lookup table. 

Do you still have this problem if you upgrade, then deactivate and reactivate the plugin?

**Comment by OllieJones** [comment]
I think this was fixed. It was an incompatibility between MariaDB 10.3 and the original code.

Please don't hesitate to open another issue you if you still have the problem.

**Comment by steveni1963** [comment]
Hi Oliver,

 

Same issue persists.  Fwol table is empty.

 

Best regards,

 

Steve

**Comment by steveni1963** [comment]
This might help:

 

WordPress database error COLLATION 'utf8mb4_unicode_520_ci' is not valid for CHARACTER SET 'latin1' for query                                                    SELECT id, value

                                                                FROM (

                                                                SELECT post_id id, meta_value COLLATE utf8mb4_unicode_520_ci value

                                                                  FROM H4j9iy_postmeta

                                                                WHERE meta_key IN ('_billing_address_index','_shipping_address_index','_billing_last_name','_billing_email','_billing_phone','_order_number','_order_number_formatted')

                                                                   AND post_id >= 130125 and post_id < 130144

 

                                                                UNION ALL

                                                                SELECT order_id id, meta_value COLLATE utf8mb4_unicode_520_ci value

                                                                  FROM H4j9iy_wc_orders_meta

                                                                WHERE meta_key IN ('_billing_address_index','_shipping_address_index','_order_number','_order_number_formatted')

                                                                   AND order_id >= 130125 and order_id < 130144

 

                                                                UNION ALL

                                                                SELECT order_id id, order_item_name COLLATE utf8mb4_unicode_520_ci value

                                                                  FROM H4j9iy_woocommerce_order_items

                                                                WHERE order_id >= 130125 and order_id < 130144

 

                                                                UNION ALL

                                                                SELECT id, billing_email COLLATE utf8mb4_unicode_520_ci value

                                                                  FROM H4j9iy_wc_orders

                                                                WHERE id >= 130125 and id < 130144

                                                                

                                                                UNION ALL

                                                                SELECT id, CAST(id AS CHAR) COLLATE utf8mb4_unicode_520_ci value

                                                                  FROM H4j9iy_wc_orders

                                                                WHERE id >= 130125 and id < 130144

                                                                

                                                                UNION ALL

                                                                SELECT id, transaction_id COLLATE utf8mb4_unicode_520_ci value

                                                                  FROM H4j9iy_wc_orders

                                                                WHERE id >= 130125 and id < 130144 AND transaction_id IS NOT NULL

                                                                

                                                                UNION ALL

                                                                SELECT order_id id, CONCAT_WS (' ', first_name, last_name, company, address_1, address_2, city, state, postcode, country) COLLATE utf8mb4_unicode_520_ci value

                                                                  FROM H4j9iy_wc_order_addresses

                                                                WHERE order_id >= 130125 and order_id < 130144

 

                                                                UNION ALL

                                                                SELECT order_id id, email COLLATE utf8mb4_unicode_520_ci value

                                                                  FROM H4j9iy_wc_order_addresses

                                                                WHERE order_id >= 130125 and order_id < 130144

**Comment by OllieJones** [comment]
Ah, that information helps, thanks. I *think* I'll be able to fix the  problem.  The root cause is a table with latin1 rather than unicode characters.

**Comment by OllieJones** [comment]
Please try version 1.1.3.

**Comment by steveni1963** [comment]
Fixed!  Works very well 😊

**Comment by OllieJones** [comment]
Thanks for letting me know. And thanks for your patience!

**Comment by steveni1963** [comment]
👍
